from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class LoginRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, otp=None):  # noqa: E501
        """LoginRequest - a model defined in OpenAPI

        :param username: The username of this LoginRequest.  # noqa: E501
        :type username: str
        :param otp: The otp of this LoginRequest.  # noqa: E501
        :type otp: float
        """
        self.openapi_types = {
            'username': str,
            'otp': float
        }

        self.attribute_map = {
            'username': 'username',
            'otp': 'otp'
        }

        self._username = username
        self._otp = otp

    @classmethod
    def from_dict(cls, dikt) -> 'LoginRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginRequest of this LoginRequest.  # noqa: E501
        :rtype: LoginRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this LoginRequest.


        :return: The username of this LoginRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this LoginRequest.


        :param username: The username of this LoginRequest.
        :type username: str
        """

        self._username = username

    @property
    def otp(self) -> float:
        """Gets the otp of this LoginRequest.


        :return: The otp of this LoginRequest.
        :rtype: float
        """
        return self._otp

    @otp.setter
    def otp(self, otp: float):
        """Sets the otp of this LoginRequest.


        :param otp: The otp of this LoginRequest.
        :type otp: float
        """

        self._otp = otp
