from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class OtpRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None):  # noqa: E501
        """OtpRequest - a model defined in OpenAPI

        :param email: The email of this OtpRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'OtpRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OtpRequest of this OtpRequest.  # noqa: E501
        :rtype: OtpRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this OtpRequest.


        :return: The email of this OtpRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this OtpRequest.


        :param email: The email of this OtpRequest.
        :type email: str
        """

        self._email = email
