from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class UserRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, emailid=None, roles=None):  # noqa: E501
        """UserRequest - a model defined in OpenAPI

        :param name: The name of this UserRequest.  # noqa: E501
        :type name: str
        :param emailid: The emailid of this UserRequest.  # noqa: E501
        :type emailid: str
        :param roles: The roles of this UserRequest.  # noqa: E501
        :type roles: List[str]
        """
        self.openapi_types = {
            'name': str,
            'emailid': str,
            'roles': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'emailid': 'emailid',
            'roles': 'roles'
        }

        self._name = name
        self._emailid = emailid
        self._roles = roles

    @classmethod
    def from_dict(cls, dikt) -> 'UserRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRequest of this UserRequest.  # noqa: E501
        :rtype: UserRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UserRequest.


        :return: The name of this UserRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserRequest.


        :param name: The name of this UserRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def emailid(self) -> str:
        """Gets the emailid of this UserRequest.


        :return: The emailid of this UserRequest.
        :rtype: str
        """
        return self._emailid

    @emailid.setter
    def emailid(self, emailid: str):
        """Sets the emailid of this UserRequest.


        :param emailid: The emailid of this UserRequest.
        :type emailid: str
        """
        if emailid is None:
            raise ValueError("Invalid value for `emailid`, must not be `None`")  # noqa: E501

        self._emailid = emailid

    @property
    def roles(self) -> List[str]:
        """Gets the roles of this UserRequest.


        :return: The roles of this UserRequest.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[str]):
        """Sets the roles of this UserRequest.


        :param roles: The roles of this UserRequest.
        :type roles: List[str]
        """
        if roles is None:
            raise ValueError("Invalid value for `roles`, must not be `None`")  # noqa: E501

        self._roles = roles
