openapi: 3.0.3
info:
  title: Dashboard API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:

  /login:
    post:
      tags:
        - login
      summary: Login and set auth cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login success
          headers:
            Set-Cookie:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
  
  /send/otp:
    post:
      tags:
        - otp
      summary: send otp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpRequest'
      responses:
        '200':
          description: sent otp  successfully
          headers:
            Set-Cookie:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
  
  /verify/otp:
    post:
      tags:
        - otp
      summary: verify otp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: verified otp successfully
          headers:
            Set-Cookie:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
    
  /user:
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object

    get:
      tags:
        - user
      summary: Get list of users
      responses:
        '200':
          description: List of users fetched successfully
          content:
            application/json:
              schema:
                type: object

    put:
      tags:
        - user
      summary: Update an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object

    delete:
      tags:
        - user
      summary: Delete a user
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                
    


components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username: { type: string }
        otp: { type: number }
    
    OtpRequest:
      type: object
      properties:
        email: {type: string}

    UserRequest:
      type: object
      required:
        - name
        - emailid
        - roles
      properties:
        name:
          type: string
          example: John Doe
        emailid:
          type: string
          format: email
          example: john.doe@example.com
        roles:
          type: array
          items:
            type: string
          example: ["admin", "editor"]


  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
