service: launchpad-backend
runtime: python310
env: standard
instance_class: F1
entrypoint: gunicorn -b :8080 main:app

handlers:
  - url: /.*
    script: auto
  - url: .*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 20

service_account: smartq-backend-784299@appspot.gserviceaccount.com

vpc_access_connector:
  name: projects/smartq-backend-784299/locations/europe-west1/connectors/launchpad-vpc-connector
