from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class LoginRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, otp=None):  # noqa: E501
        """LoginRequest - a model defined in OpenAPI

        :param email: The email of this LoginRequest.  # noqa: E501
        :type email: str
        :param otp: The otp of this LoginRequest.  # noqa: E501
        :type otp: str
        """
        self.openapi_types = {
            'email': str,
            'otp': str
        }

        self.attribute_map = {
            'email': 'email',
            'otp': 'otp'
        }

        self._email = email
        self._otp = otp

    @classmethod
    def from_dict(cls, dikt) -> 'LoginRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginRequest of this LoginRequest.  # noqa: E501
        :rtype: LoginRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this LoginRequest.


        :return: The email of this LoginRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this LoginRequest.


        :param email: The email of this LoginRequest.
        :type email: str
        """

        self._email = email

    @property
    def otp(self) -> str:
        """Gets the otp of this LoginRequest.


        :return: The otp of this LoginRequest.
        :rtype: str
        """
        return self._otp

    @otp.setter
    def otp(self, otp: str):
        """Sets the otp of this LoginRequest.


        :param otp: The otp of this LoginRequest.
        :type otp: str
        """

        self._otp = otp
