from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model import Model
from .. import util


class OrganizationRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, sector=None, unit_code=None, organization_logo=None):  # noqa: E501
        """OrganizationRequest - a model defined in OpenAPI

        :param id: The id of this OrganizationRequest.  # noqa: E501
        :type id: int
        :param name: The name of this OrganizationRequest.  # noqa: E501
        :type name: str
        :param description: The description of this OrganizationRequest.  # noqa: E501
        :type description: str
        :param sector: The sector of this OrganizationRequest.  # noqa: E501
        :type sector: str
        :param unit_code: The unit_code of this OrganizationRequest.  # noqa: E501
        :type unit_code: str
        :param organization_logo: The organization_logo of this OrganizationRequest.  # noqa: E501
        :type organization_logo: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'description': str,
            'sector': str,
            'unit_code': str,
            'organization_logo': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'sector': 'sector',
            'unit_code': 'unit_code',
            'organization_logo': 'organization_logo'
        }

        self._id = id
        self._name = name
        self._description = description
        self._sector = sector
        self._unit_code = unit_code
        self._organization_logo = organization_logo

    @classmethod
    def from_dict(cls, dikt) -> 'OrganizationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrganizationRequest of this OrganizationRequest.  # noqa: E501
        :rtype: OrganizationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this OrganizationRequest.


        :return: The id of this OrganizationRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this OrganizationRequest.


        :param id: The id of this OrganizationRequest.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this OrganizationRequest.


        :return: The name of this OrganizationRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OrganizationRequest.


        :param name: The name of this OrganizationRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this OrganizationRequest.


        :return: The description of this OrganizationRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OrganizationRequest.


        :param description: The description of this OrganizationRequest.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def sector(self) -> str:
        """Gets the sector of this OrganizationRequest.


        :return: The sector of this OrganizationRequest.
        :rtype: str
        """
        return self._sector

    @sector.setter
    def sector(self, sector: str):
        """Sets the sector of this OrganizationRequest.


        :param sector: The sector of this OrganizationRequest.
        :type sector: str
        """
        if sector is None:
            raise ValueError("Invalid value for `sector`, must not be `None`")  # noqa: E501

        self._sector = sector

    @property
    def unit_code(self) -> str:
        """Gets the unit_code of this OrganizationRequest.


        :return: The unit_code of this OrganizationRequest.
        :rtype: str
        """
        return self._unit_code

    @unit_code.setter
    def unit_code(self, unit_code: str):
        """Sets the unit_code of this OrganizationRequest.


        :param unit_code: The unit_code of this OrganizationRequest.
        :type unit_code: str
        """
        if unit_code is None:
            raise ValueError("Invalid value for `unit_code`, must not be `None`")  # noqa: E501

        self._unit_code = unit_code

    @property
    def organization_logo(self) -> str:
        """Gets the organization_logo of this OrganizationRequest.


        :return: The organization_logo of this OrganizationRequest.
        :rtype: str
        """
        return self._organization_logo

    @organization_logo.setter
    def organization_logo(self, organization_logo: str):
        """Sets the organization_logo of this OrganizationRequest.


        :param organization_logo: The organization_logo of this OrganizationRequest.
        :type organization_logo: str
        """

        self._organization_logo = organization_logo
