from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model import Model
from .. import util


class PageRequestSectionsInnerFieldsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, field_id=None, field_name=None, field_value=None):  # noqa: E501
        """PageRequestSectionsInnerFieldsInner - a model defined in OpenAPI

        :param field_id: The field_id of this PageRequestSectionsInnerFieldsInner.  # noqa: E501
        :type field_id: int
        :param field_name: The field_name of this PageRequestSectionsInnerFieldsInner.  # noqa: E501
        :type field_name: str
        :param field_value: The field_value of this PageRequestSectionsInnerFieldsInner.  # noqa: E501
        :type field_value: str
        """
        self.openapi_types = {
            'field_id': int,
            'field_name': str,
            'field_value': str
        }

        self.attribute_map = {
            'field_id': 'field_id',
            'field_name': 'field_name',
            'field_value': 'field_value'
        }

        self._field_id = field_id
        self._field_name = field_name
        self._field_value = field_value

    @classmethod
    def from_dict(cls, dikt) -> 'PageRequestSectionsInnerFieldsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageRequest_sections_inner_fields_inner of this PageRequestSectionsInnerFieldsInner.  # noqa: E501
        :rtype: PageRequestSectionsInnerFieldsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field_id(self) -> int:
        """Gets the field_id of this PageRequestSectionsInnerFieldsInner.


        :return: The field_id of this PageRequestSectionsInnerFieldsInner.
        :rtype: int
        """
        return self._field_id

    @field_id.setter
    def field_id(self, field_id: int):
        """Sets the field_id of this PageRequestSectionsInnerFieldsInner.


        :param field_id: The field_id of this PageRequestSectionsInnerFieldsInner.
        :type field_id: int
        """

        self._field_id = field_id

    @property
    def field_name(self) -> str:
        """Gets the field_name of this PageRequestSectionsInnerFieldsInner.


        :return: The field_name of this PageRequestSectionsInnerFieldsInner.
        :rtype: str
        """
        return self._field_name

    @field_name.setter
    def field_name(self, field_name: str):
        """Sets the field_name of this PageRequestSectionsInnerFieldsInner.


        :param field_name: The field_name of this PageRequestSectionsInnerFieldsInner.
        :type field_name: str
        """
        if field_name is None:
            raise ValueError("Invalid value for `field_name`, must not be `None`")  # noqa: E501

        self._field_name = field_name

    @property
    def field_value(self) -> str:
        """Gets the field_value of this PageRequestSectionsInnerFieldsInner.


        :return: The field_value of this PageRequestSectionsInnerFieldsInner.
        :rtype: str
        """
        return self._field_value

    @field_value.setter
    def field_value(self, field_value: str):
        """Sets the field_value of this PageRequestSectionsInnerFieldsInner.


        :param field_value: The field_value of this PageRequestSectionsInnerFieldsInner.
        :type field_value: str
        """
        if field_value is None:
            raise ValueError("Invalid value for `field_value`, must not be `None`")  # noqa: E501

        self._field_value = field_value
