from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model import Model
from .page_request_sections_inner import PageRequestSectionsInner
from .. import util

from .page_request_sections_inner import PageRequestSectionsInner  # noqa: E501

class PageRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, page_name=None, site_id=None, status=None, sections=None):  # noqa: E501
        """PageRequest - a model defined in OpenAPI

        :param id: The id of this PageRequest.  # noqa: E501
        :type id: int
        :param page_name: The page_name of this PageRequest.  # noqa: E501
        :type page_name: str
        :param site_id: The site_id of this PageRequest.  # noqa: E501
        :type site_id: int
        :param status: The status of this PageRequest.  # noqa: E501
        :type status: str
        :param sections: The sections of this PageRequest.  # noqa: E501
        :type sections: List[PageRequestSectionsInner]
        """
        self.openapi_types = {
            'id': int,
            'page_name': str,
            'site_id': int,
            'status': str,
            'sections': List[PageRequestSectionsInner]
        }

        self.attribute_map = {
            'id': 'id',
            'page_name': 'page_name',
            'site_id': 'site_id',
            'status': 'status',
            'sections': 'sections'
        }

        self._id = id
        self._page_name = page_name
        self._site_id = site_id
        self._status = status
        self._sections = sections

    @classmethod
    def from_dict(cls, dikt) -> 'PageRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageRequest of this PageRequest.  # noqa: E501
        :rtype: PageRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PageRequest.


        :return: The id of this PageRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PageRequest.


        :param id: The id of this PageRequest.
        :type id: int
        """

        self._id = id

    @property
    def page_name(self) -> str:
        """Gets the page_name of this PageRequest.


        :return: The page_name of this PageRequest.
        :rtype: str
        """
        return self._page_name

    @page_name.setter
    def page_name(self, page_name: str):
        """Sets the page_name of this PageRequest.


        :param page_name: The page_name of this PageRequest.
        :type page_name: str
        """
        if page_name is None:
            raise ValueError("Invalid value for `page_name`, must not be `None`")  # noqa: E501

        self._page_name = page_name

    @property
    def site_id(self) -> int:
        """Gets the site_id of this PageRequest.


        :return: The site_id of this PageRequest.
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: int):
        """Sets the site_id of this PageRequest.


        :param site_id: The site_id of this PageRequest.
        :type site_id: int
        """
        if site_id is None:
            raise ValueError("Invalid value for `site_id`, must not be `None`")  # noqa: E501

        self._site_id = site_id

    @property
    def status(self) -> str:
        """Gets the status of this PageRequest.


        :return: The status of this PageRequest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this PageRequest.


        :param status: The status of this PageRequest.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def sections(self) -> List[PageRequestSectionsInner]:
        """Gets the sections of this PageRequest.

        List of sections belonging to the page  # noqa: E501

        :return: The sections of this PageRequest.
        :rtype: List[PageRequestSectionsInner]
        """
        return self._sections

    @sections.setter
    def sections(self, sections: List[PageRequestSectionsInner]):
        """Sets the sections of this PageRequest.

        List of sections belonging to the page  # noqa: E501

        :param sections: The sections of this PageRequest.
        :type sections: List[PageRequestSectionsInner]
        """

        self._sections = sections
