from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api.models.page_request_sections_inner_fields_inner import PageRequestSectionsInnerFieldsInner
from launchpad_api import util

from launchpad_api.models.page_request_sections_inner_fields_inner import PageRequestSectionsInnerFieldsInner  # noqa: E501

class PageRequestSectionsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, section_id=None, section_name=None, fields=None):  # noqa: E501
        """PageRequestSectionsInner - a model defined in OpenAPI

        :param section_id: The section_id of this PageRequestSectionsInner.  # noqa: E501
        :type section_id: int
        :param section_name: The section_name of this PageRequestSectionsInner.  # noqa: E501
        :type section_name: str
        :param fields: The fields of this PageRequestSectionsInner.  # noqa: E501
        :type fields: List[PageRequestSectionsInnerFieldsInner]
        """
        self.openapi_types = {
            'section_id': int,
            'section_name': str,
            'fields': List[PageRequestSectionsInnerFieldsInner]
        }

        self.attribute_map = {
            'section_id': 'section_id',
            'section_name': 'section_name',
            'fields': 'fields'
        }

        self._section_id = section_id
        self._section_name = section_name
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'PageRequestSectionsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageRequest_sections_inner of this PageRequestSectionsInner.  # noqa: E501
        :rtype: PageRequestSectionsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def section_id(self) -> int:
        """Gets the section_id of this PageRequestSectionsInner.


        :return: The section_id of this PageRequestSectionsInner.
        :rtype: int
        """
        return self._section_id

    @section_id.setter
    def section_id(self, section_id: int):
        """Sets the section_id of this PageRequestSectionsInner.


        :param section_id: The section_id of this PageRequestSectionsInner.
        :type section_id: int
        """

        self._section_id = section_id

    @property
    def section_name(self) -> str:
        """Gets the section_name of this PageRequestSectionsInner.


        :return: The section_name of this PageRequestSectionsInner.
        :rtype: str
        """
        return self._section_name

    @section_name.setter
    def section_name(self, section_name: str):
        """Sets the section_name of this PageRequestSectionsInner.


        :param section_name: The section_name of this PageRequestSectionsInner.
        :type section_name: str
        """
        if section_name is None:
            raise ValueError("Invalid value for `section_name`, must not be `None`")  # noqa: E501

        self._section_name = section_name

    @property
    def fields(self) -> List[PageRequestSectionsInnerFieldsInner]:
        """Gets the fields of this PageRequestSectionsInner.

        List of fields under this section  # noqa: E501

        :return: The fields of this PageRequestSectionsInner.
        :rtype: List[PageRequestSectionsInnerFieldsInner]
        """
        return self._fields

    @fields.setter
    def fields(self, fields: List[PageRequestSectionsInnerFieldsInner]):
        """Sets the fields of this PageRequestSectionsInner.

        List of fields under this section  # noqa: E501

        :param fields: The fields of this PageRequestSectionsInner.
        :type fields: List[PageRequestSectionsInnerFieldsInner]
        """
        if fields is None:
            raise ValueError("Invalid value for `fields`, must not be `None`")  # noqa: E501

        self._fields = fields
