from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class PageRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page_name=None, site_id=None, id=None):  # noqa: E501
        """PageRequest - a model defined in OpenAPI

        :param page_name: The page_name of this PageRequest.  # noqa: E501
        :type page_name: str
        :param site_id: The site_id of this PageRequest.  # noqa: E501
        :type site_id: int
        :param id: The id of this PageRequest.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'page_name': str,
            'site_id': int,
            'id': int
        }

        self.attribute_map = {
            'page_name': 'page_name',
            'site_id': 'site_id',
            'id': 'id'
        }

        self._page_name = page_name
        self._site_id = site_id
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'PageRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageRequest of this PageRequest.  # noqa: E501
        :rtype: PageRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page_name(self) -> str:
        """Gets the page_name of this PageRequest.


        :return: The page_name of this PageRequest.
        :rtype: str
        """
        return self._page_name

    @page_name.setter
    def page_name(self, page_name: str):
        """Sets the page_name of this PageRequest.


        :param page_name: The page_name of this PageRequest.
        :type page_name: str
        """
        if page_name is None:
            raise ValueError("Invalid value for `page_name`, must not be `None`")  # noqa: E501

        self._page_name = page_name

    @property
    def site_id(self) -> int:
        """Gets the site_id of this PageRequest.


        :return: The site_id of this PageRequest.
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: int):
        """Sets the site_id of this PageRequest.


        :param site_id: The site_id of this PageRequest.
        :type site_id: int
        """
        if site_id is None:
            raise ValueError("Invalid value for `site_id`, must not be `None`")  # noqa: E501

        self._site_id = site_id

    @property
    def id(self) -> int:
        """Gets the id of this PageRequest.


        :return: The id of this PageRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PageRequest.


        :param id: The id of this PageRequest.
        :type id: int
        """

        self._id = id
