from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from launchpad_api.models.base_model import Model
from launchpad_api import util


class SectionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, section_name=None, page_id=None, fields=None):  # noqa: E501
        """SectionRequest - a model defined in OpenAPI

        :param section_name: The section_name of this SectionRequest.  # noqa: E501
        :type section_name: str
        :param page_id: The page_id of this SectionRequest.  # noqa: E501
        :type page_id: int
        :param fields: The fields of this SectionRequest.  # noqa: E501
        :type fields: object
        """
        self.openapi_types = {
            'section_name': str,
            'page_id': int,
            'fields': object
        }

        self.attribute_map = {
            'section_name': 'section_name',
            'page_id': 'page_id',
            'fields': 'fields'
        }

        self._section_name = section_name
        self._page_id = page_id
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'SectionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SectionRequest of this SectionRequest.  # noqa: E501
        :rtype: SectionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def section_name(self) -> str:
        """Gets the section_name of this SectionRequest.


        :return: The section_name of this SectionRequest.
        :rtype: str
        """
        return self._section_name

    @section_name.setter
    def section_name(self, section_name: str):
        """Sets the section_name of this SectionRequest.


        :param section_name: The section_name of this SectionRequest.
        :type section_name: str
        """
        if section_name is None:
            raise ValueError("Invalid value for `section_name`, must not be `None`")  # noqa: E501

        self._section_name = section_name

    @property
    def page_id(self) -> int:
        """Gets the page_id of this SectionRequest.


        :return: The page_id of this SectionRequest.
        :rtype: int
        """
        return self._page_id

    @page_id.setter
    def page_id(self, page_id: int):
        """Sets the page_id of this SectionRequest.


        :param page_id: The page_id of this SectionRequest.
        :type page_id: int
        """
        if page_id is None:
            raise ValueError("Invalid value for `page_id`, must not be `None`")  # noqa: E501

        self._page_id = page_id

    @property
    def fields(self) -> object:
        """Gets the fields of this SectionRequest.


        :return: The fields of this SectionRequest.
        :rtype: object
        """
        return self._fields

    @fields.setter
    def fields(self, fields: object):
        """Sets the fields of this SectionRequest.


        :param fields: The fields of this SectionRequest.
        :type fields: object
        """

        self._fields = fields
