from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model import Model
from .. import util


class SiteRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, id=None):  # noqa: E501
        """SiteRequest - a model defined in OpenAPI

        :param status: The status of this SiteRequest.  # noqa: E501
        :type status: str
        :param id: The id of this SiteRequest.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'status': str,
            'id': int
        }

        self.attribute_map = {
            'status': 'status',
            'id': 'id'
        }

        self._status = status
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'SiteRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SiteRequest of this SiteRequest.  # noqa: E501
        :rtype: SiteRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this SiteRequest.


        :return: The status of this SiteRequest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this SiteRequest.


        :param status: The status of this SiteRequest.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def id(self) -> int:
        """Gets the id of this SiteRequest.


        :return: The id of this SiteRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SiteRequest.


        :param id: The id of this SiteRequest.
        :type id: int
        """

        self._id = id
